---
title: "Online experiments - lecture 1"
author: Justin Sulik
date: 15/04/21
output: 
  ioslides_presentation:
    keep_md: true 
    widescreen: true
    smaller: true
  
---

## Overview

- Introductions
- Course overview
- What is X-Phi?
- HTML + CSS + JS

## Course overview

- This is primarily a methods course
  - how to design + code an experiment to run online

- But it's also a philosophy course
  - how to poke at a theory by gathering data

- We're casting a fairly broad net
  - your challenge is to find a bridge or have a shift in perspective
  
- It's up to you how much of a theorist or coder you want to be

## Practical advice

- This is an online course
- We're learning about coding online experiments
- Embrace being online: learn with youtube, twitter, games

## What is X-Phi?

#### "Experimental philosophy is a new interdisciplinary field that uses **methods** normally associated with psychology to investigate **questions** normally associated with philosophy." 

- Knobe et al., *Annu. Rev. Psychol.* 2012. 63:81–99.

## What is X-Phi?

###

## What is X-Phi?

